# Generated by Django 5.2 on 2025-04-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('lugar', models.CharField(max_length=100)),
                ('ubicacion', models.TextField()),
                ('es_multiple', models.BooleanField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
