# Generated by Django 5.2 on 2025-05-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_club', models.CharField(max_length=100)),
                ('imagen_club', models.TextField(blank=True, null=True)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('slogan', models.CharField(blank=True, max_length=150, null=True)),
                ('presidente', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('ubicacion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
