# Generated by Django 5.2 on 2025-05-14 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_equipo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='equipo',
            table='equipos',
        ),
    ]
