# Generated by Django 5.2 on 2025-05-14 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_equipo_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='presidente',
            new_name='nombre_presidente',
        ),
    ]
